IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        Wait(2)
        MoveViewObject("finsol01",8)
        Wait(1)
        ActionOverride("finsol01",ForceSpell(Player1,SAREVOK_SOULSTEAL))
        Wait(2)
        ActionOverride("finsol01",ForceSpell("lrirenic",SAREVOK_SOULSTEAL))
        Wait(2)
        CreateVisualEffectObject("SPGFLSH1","lrirenic")
        Wait(4)
        ActionOverride("finsol01",StartDialogueNoSet(Player1))
        EndCutSceneMode()
END
