LR\sound\oggdec.exe LR\sound\deva1.ogg
LR\sound\oggdec.exe LR\sound\deva2.ogg 
LR\sound\oggdec.exe LR\sound\deva3.ogg 
LR\sound\oggdec.exe LR\sound\deva4.ogg 
LR\sound\oggdec.exe LR\sound\deva5.ogg 
LR\sound\oggdec.exe LR\sound\deva6.ogg
LR\sound\oggdec.exe LR\sound\deva7.ogg
LR\sound\oggdec.exe LR\sound\deva8.ogg
LR\sound\oggdec.exe LR\sound\nymph11.ogg
LR\sound\oggdec.exe LR\sound\nymph118.ogg
LR\sound\oggdec.exe LR\sound\nymph12.ogg
LR\sound\oggdec.exe LR\sound\nymph14.ogg
LR\sound\oggdec.exe LR\sound\nymph16.ogg
LR\sound\oggdec.exe LR\sound\nymph19.ogg
LR\sound\oggdec.exe LR\sound\nymph21.ogg
LR\sound\oggdec.exe LR\sound\nymph22.ogg
LR\sound\oggdec.exe LR\sound\nymph23.ogg
LR\sound\oggdec.exe LR\sound\nymph26.ogg
LR\sound\oggdec.exe LR\sound\nymph27.ogg
LR\sound\oggdec.exe LR\sound\nymph28.ogg
LR\sound\oggdec.exe LR\sound\nymph210.ogg
LR\sound\oggdec.exe LR\sound\nymph113.ogg
LR\sound\oggdec.exe LR\sound\nymph116.ogg
LR\sound\oggdec.exe LR\sound\nymph120.ogg
LR\sound\oggdec.exe LR\sound\nymph122.ogg
LR\sound\oggdec.exe LR\sound\nymph123.ogg
LR\sound\oggdec.exe LR\sound\nymph34.ogg
LR\sound\oggdec.exe LR\sound\nymph35.ogg
LR\sound\oggdec.exe LR\sound\nymph36.ogg
LR\sound\oggdec.exe LR\sound\nymph37.ogg
LR\sound\oggdec.exe LR\sound\nymph39.ogg
LR\sound\oggdec.exe LR\sound\nymph310.ogg
LR\sound\oggdec.exe LR\sound\nymph311.ogg
LR\sound\oggdec.exe LR\sound\nymph313.ogg
LR\sound\oggdec.exe LR\sound\nymph314.ogg
LR\sound\oggdec.exe LR\sound\nymph315.ogg
LR\sound\oggdec.exe LR\sound\nymph317.ogg
LR\sound\oggdec.exe LR\sound\nymph319.ogg
LR\sound\oggdec.exe LR\sound\nymph323.ogg
LR\sound\oggdec.exe LR\sound\mary.ogg  

Copy LR\sound\deva1.wav override
Copy LR\sound\deva2.wav override
Copy LR\sound\deva3.wav override
Copy LR\sound\deva4.wav override
Copy LR\sound\deva5.wav override
Copy LR\sound\deva6.wav override
Copy LR\sound\deva7.wav override
Copy LR\sound\deva8.wav override
Copy LR\sound\nymph11.wav override
Copy LR\sound\nymph118.wav override
Copy LR\sound\nymph12.wav override
Copy LR\sound\nymph14.wav override
Copy LR\sound\nymph16.wav override
Copy LR\sound\nymph19.wav override
Copy LR\sound\nymph21.wav override
Copy LR\sound\nymph22.wav override
Copy LR\sound\nymph23.wav override
Copy LR\sound\nymph26.wav override
Copy LR\sound\nymph27.wav override
Copy LR\sound\nymph28.wav override
Copy LR\sound\nymph210.wav override
Copy LR\sound\nymph113.wav override
Copy LR\sound\nymph116.wav override
Copy LR\sound\nymph120.wav override
Copy LR\sound\nymph122.wav override
Copy LR\sound\nymph123.wav override
Copy LR\sound\nymph34.wav override
Copy LR\sound\nymph35.wav override
Copy LR\sound\nymph36.wav override
Copy LR\sound\nymph37.wav override
Copy LR\sound\nymph39.wav override
Copy LR\sound\nymph310.wav override
Copy LR\sound\nymph311.wav override
Copy LR\sound\nymph313.wav override
Copy LR\sound\nymph314.wav override
Copy LR\sound\nymph315.wav override
Copy LR\sound\nymph317.wav override
Copy LR\sound\nymph319.wav override
Copy LR\sound\nymph323.wav override
Copy LR\sound\mary.wav override

Del LR\sound\deva1.wav
Del LR\sound\deva2.wav
Del LR\sound\deva3.wav
Del LR\sound\deva4.wav
Del LR\sound\deva5.wav
Del LR\sound\deva6.wav
Del LR\sound\deva7.wav
Del LR\sound\deva8.wav
Del LR\sound\nymph11.wav
Del LR\sound\nymph118.wav
Del LR\sound\nymph12.wav
Del LR\sound\nymph14.wav
Del LR\sound\nymph16.wav
Del LR\sound\nymph19.wav
Del LR\sound\nymph21.wav
Del LR\sound\nymph22.wav
Del LR\sound\nymph23.wav
Del LR\sound\nymph26.wav
Del LR\sound\nymph27.wav
Del LR\sound\nymph28.wav
Del LR\sound\nymph210.wav
Del LR\sound\nymph113.wav
Del LR\sound\nymph116.wav
Del LR\sound\nymph120.wav
Del LR\sound\nymph122.wav
Del LR\sound\nymph123.wav
Del LR\sound\nymph34.wav
Del LR\sound\nymph35.wav
Del LR\sound\nymph36.wav
Del LR\sound\nymph37.wav
Del LR\sound\nymph39.wav
Del LR\sound\nymph310.wav
Del LR\sound\nymph311.wav
Del LR\sound\nymph313.wav
Del LR\sound\nymph314.wav
Del LR\sound\nymph315.wav
Del LR\sound\nymph317.wav
Del LR\sound\nymph319.wav
Del LR\sound\nymph323.wav
Del LR\sound\mary.wav


