MD Music\MxAbys
MD Music\MxElle
MD Music\MxHeal
MD Music\MxIren
MD Music\MxTroll
LR\sound\oggdec.exe LR\sound\MxAbysA.ogg
LR\sound\oggdec.exe LR\sound\MxElleA.ogg
LR\sound\oggdec.exe LR\sound\MxHealA.ogg
LR\sound\oggdec.exe LR\sound\MxirenA.ogg
LR\sound\oggdec.exe LR\sound\MxTrollA.ogg
LR\sound\SND2ACM.exe -wav LR\sound\MxAbysA.wav LR\sound\MxAbysA.acm
LR\sound\SND2ACM.exe -wav LR\sound\MxElleA.wav LR\sound\MxElleA.acm
LR\sound\SND2ACM.exe -wav LR\sound\MxHealA.wav LR\sound\MxHealA.acm
LR\sound\SND2ACM.exe -wav LR\sound\MxIrenA.wav LR\sound\MxIrenA.acm
LR\sound\SND2ACM.exe -wav LR\sound\MxTrollA.wav LR\sound\MxTrollA.acm
Copy LR\sound\MxAbysA.acm music\MxAbys
Copy LR\sound\MxElleA.acm music\MxElle
Copy LR\sound\MxHealA.acm music\MxHeal
Copy LR\sound\MxIrenA.acm music\MxIren
Copy LR\sound\MxTrollA.acm music\MxTroll
Del LR\sound\MxTrollA.acm
Del LR\sound\MxAbysA.wav
Del LR\sound\MxElleA.wav
Del LR\sound\MxHealA.wav
Del LR\sound\MxIrenA.wav
Del LR\sound\MxTrollA.wav
Del LR\sound\MxAbysA.acm
Del LR\sound\MxElleA.acm
Del LR\sound\MxHealA.acm
Del LR\sound\MxIrenA.acm

