IF
  True()
THEN
  RESPONSE #100
    CutSceneId("finsol01")
    Wait(1)
    CreateVisualEffect("SPGRWHRL",[1352.1134])
    Wait(1)
    CreateVisualEffect("SPANISUM",[1352.1134])
    Wait(1)
    CreateCreature("LRavatar",[1352.1134],7)
    ActionOverride("LRavatar",FaceObject("lrirenic"))
    ActionOverride("lrirenic",FaceObject("LRavatar"))
    Wait(3)
    PlaySong(%MxElle%)
    ActionOverride("LRavatar",StartDialogueNoSet("LRavatar"))
END



