IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		FaceObject("demogor3")  // Demogorgon
		MoveViewObject("demogor3",5)  // Demogorgon
		SmallWait(1)
		ActionOverride("demogor3",DisplayStringHead(Myself,@16))  // I shall see you again in a few days, Exile. Perchance the contrast between what you are, and what you may become in my service, will make you more compliant.
		Kill(Player1)
		Wait(5)
		EndCutSceneMode()
END

